import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  BOOKING_ENDS_AT_FIELD_UNIVERSAL_IDENTIFIER,
  BOOKING_FEE_FIELD_UNIVERSAL_IDENTIFIER,
  BOOKING_LOCATION_CLIENT_SITE_OPTION_ID,
  BOOKING_LOCATION_FIELD_UNIVERSAL_IDENTIFIER,
  BOOKING_LOCATION_OFFICE_OPTION_ID,
  BOOKING_LOCATION_ONLINE_OPTION_ID,
  BOOKING_NOTES_FIELD_UNIVERSAL_IDENTIFIER,
  BOOKING_OBJECT_UNIVERSAL_IDENTIFIER,
  BOOKING_SERVICE_CONSULTATION_OPTION_ID,
  BOOKING_SERVICE_FIELD_UNIVERSAL_IDENTIFIER,
  BOOKING_SERVICE_FOLLOW_UP_OPTION_ID,
  BOOKING_SERVICE_NOTARIZATION_OPTION_ID,
  BOOKING_SERVICE_SIGNING_OPTION_ID,
  BOOKING_STARTS_AT_FIELD_UNIVERSAL_IDENTIFIER,
  BOOKING_STATUS_CANCELLED_OPTION_ID,
  BOOKING_STATUS_COMPLETED_OPTION_ID,
  BOOKING_STATUS_CONFIRMED_OPTION_ID,
  BOOKING_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  BOOKING_STATUS_NO_SHOW_OPTION_ID,
  BOOKING_STATUS_REQUESTED_OPTION_ID,
  BOOKING_STATUS_RESCHEDULED_OPTION_ID,
  BOOKING_TITLE_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

// Ours, not Twenty's CalendarEvent (D5): that object mirrors Google and
// Microsoft, and a booking needs its own lifecycle and its own relations.
export default defineObject({
  universalIdentifier: BOOKING_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'booking',
  namePlural: 'bookings',
  labelSingular: 'Booking',
  labelPlural: 'Bookings',
  description: 'A consultation or appointment with a client',
  icon: 'IconCalendarEvent',
  labelIdentifierFieldMetadataUniversalIdentifier:
    BOOKING_TITLE_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: BOOKING_TITLE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'title',
      label: 'Booking',
      description: 'What it is, as it should read in a calendar cell',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: BOOKING_STARTS_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'startsAt',
      label: 'Starts',
      icon: 'IconClock',
    },
    {
      universalIdentifier: BOOKING_ENDS_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'endsAt',
      label: 'Ends',
      icon: 'IconClockStop',
    },
    {
      universalIdentifier: BOOKING_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgressCheck',
      defaultValue: "'REQUESTED'",
      options: [
        {
          id: BOOKING_STATUS_REQUESTED_OPTION_ID,
          value: 'REQUESTED',
          label: 'Requested',
          position: 0,
          color: 'orange',
        },
        {
          id: BOOKING_STATUS_CONFIRMED_OPTION_ID,
          value: 'CONFIRMED',
          label: 'Confirmed',
          position: 1,
          color: 'green',
        },
        {
          id: BOOKING_STATUS_RESCHEDULED_OPTION_ID,
          value: 'RESCHEDULED',
          label: 'Rescheduled',
          position: 2,
          color: 'blue',
        },
        {
          id: BOOKING_STATUS_COMPLETED_OPTION_ID,
          value: 'COMPLETED',
          label: 'Completed',
          position: 3,
          color: 'gray',
        },
        {
          id: BOOKING_STATUS_CANCELLED_OPTION_ID,
          value: 'CANCELLED',
          label: 'Cancelled',
          position: 4,
          color: 'gray',
        },
        // Earns its place: nobody adds it until the third time it costs an hour.
        {
          id: BOOKING_STATUS_NO_SHOW_OPTION_ID,
          value: 'NO_SHOW',
          label: 'No show',
          position: 5,
          color: 'red',
        },
      ],
    },
    {
      universalIdentifier: BOOKING_SERVICE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'service',
      label: 'Service',
      icon: 'IconBriefcase',
      defaultValue: "'CONSULTATION'",
      options: [
        {
          id: BOOKING_SERVICE_CONSULTATION_OPTION_ID,
          value: 'CONSULTATION',
          label: 'Initial consultation',
          position: 0,
          color: 'blue',
        },
        {
          id: BOOKING_SERVICE_FOLLOW_UP_OPTION_ID,
          value: 'FOLLOW_UP',
          label: 'Follow-up',
          position: 1,
          color: 'turquoise',
        },
        {
          id: BOOKING_SERVICE_NOTARIZATION_OPTION_ID,
          value: 'NOTARIZATION',
          label: 'Notarization',
          position: 2,
          color: 'purple',
        },
        {
          id: BOOKING_SERVICE_SIGNING_OPTION_ID,
          value: 'SIGNING',
          label: 'Document signing',
          position: 3,
          color: 'green',
        },
      ],
    },
    {
      universalIdentifier: BOOKING_LOCATION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'location',
      label: 'Location',
      icon: 'IconMapPin',
      defaultValue: "'OFFICE'",
      options: [
        {
          id: BOOKING_LOCATION_OFFICE_OPTION_ID,
          value: 'OFFICE',
          label: 'Office',
          position: 0,
          color: 'blue',
        },
        {
          id: BOOKING_LOCATION_ONLINE_OPTION_ID,
          value: 'ONLINE',
          label: 'Online',
          position: 1,
          color: 'turquoise',
        },
        {
          id: BOOKING_LOCATION_CLIENT_SITE_OPTION_ID,
          value: 'CLIENT_SITE',
          label: 'Client site',
          position: 2,
          color: 'orange',
        },
      ],
    },
    {
      universalIdentifier: BOOKING_FEE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'fee',
      label: 'Fee',
      description: 'Charged for the appointment itself, if anything',
      icon: 'IconCoin',
    },
    {
      universalIdentifier: BOOKING_NOTES_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'notes',
      label: 'Notes',
      icon: 'IconNote',
    },
  ],
});
